services:
  api:
    build:
      context: api
      target: builder
    secrets:
      - APP_DB_PASSWORD
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - APP_DB_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD_FILE=/run/secrets/APP_DB_PASSWORD
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: nginx
    volumes:
      - type: bind
        source: ./web-proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on: 
      - api

volumes:
  db-data:

secrets:
  APP_DB_PASSWORD:
    file: database/password.txt